import contextlib
import logging
import re
from datetime import UTC, datetime
from pathlib import Path

from mymise.models import RegistrationResult, ResolutionResult

logger = logging.getLogger(__name__)

# Allowlisted command prefixes for bootstrap.sh.
# Anything not matching one of these is treated as untrusted and skipped to prevent
# shell command injection via the UnresolvedTool.suggested_actions field.
_ALLOWED_INSTALL_PREFIXES: tuple[str, ...] = (
    "apt install",
    "apt-get install",
    "snap install",
    "cargo install",
    "npm install",
    "npm i ",
    "pip install",
    "pipx install",
    "go install",
    "uv tool install",
    "brew install",
)

# Shell metacharacters that signal injection attempts. A legitimate `<pkg-mgr> install <name>`
# command never needs these.
_SHELL_INJECTION_CHARS: tuple[str, ...] = (";", "&", "|", "`", "$(", ">", "<", "\n", "\r")


def _is_safe_install_command(cmd: str) -> bool:
    """Return True if cmd matches an allowlisted install prefix and contains no shell metacharacters."""
    cmd = cmd.strip()
    if not cmd:
        return False
    if any(meta in cmd for meta in _SHELL_INJECTION_CHARS):
        return False
    return any(cmd.startswith(prefix) for prefix in _ALLOWED_INSTALL_PREFIXES)


class Registrar:
    def __init__(
        self, result: ResolutionResult, output_dir: Path | str = ".", shorthands_file: str = "shorthands.toml"
    ):
        self.result = result
        self.output_dir = Path(output_dir)
        self.shorthands_file = shorthands_file
        self.version = "0.1.0"  # Could be loaded from pyproject.toml in a real scenario

    def generate_artifacts(self) -> RegistrationResult:
        """Generate mise.toml, shorthands.toml, and bootstrap.sh."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        github_pattern = re.compile(r"github:[a-zA-Z0-9\-\._/]+")

        # Calculate counts for summary/result
        shorthands_count = 0
        bootstrap_count = 0

        for ut in self.result.unresolved:
            is_github = any(github_pattern.search(action) for action in ut.suggested_actions)
            if is_github:
                shorthands_count += 1
                continue
            # Only count as bootstrap-emitted if at least one suggested_action passes the
            # install-command allowlist; this matches what _generate_bootstrap_sh actually writes.
            if any(_is_safe_install_command(action) for action in ut.suggested_actions):
                bootstrap_count += 1

        artifacts = {}
        errors = []

        try:
            artifacts["mise.toml"] = str(self._generate_mise_toml())
        except Exception as e:
            errors.append(f"Failed to generate mise.toml: {e}")

        try:
            artifacts[self.shorthands_file] = str(self._generate_shorthands_toml())
        except Exception as e:
            errors.append(f"Failed to generate {self.shorthands_file}: {e}")

        try:
            artifacts["bootstrap.sh"] = str(self._generate_bootstrap_sh())
        except Exception as e:
            errors.append(f"Failed to generate bootstrap.sh: {e}")

        return RegistrationResult(
            registration_timestamp=datetime.now(),
            artifacts=artifacts,
            resolved_count=len(self.result.resolved),
            shorthands_count=shorthands_count,
            bootstrap_count=bootstrap_count,
            partial_failure=len(errors) > 0,
            errors=errors,
        )

    def _get_header(self) -> str:
        timestamp = datetime.now(UTC).isoformat(sep=" ", timespec="seconds")
        return (
            f"# Generated by mymise v{self.version}\n"
            f"# Timestamp: {timestamp}\n"
            "# ----------------------------------------------------------------------------\n"
        )

    def _generate_mise_toml(self) -> Path:
        path = self.output_dir / "mise.toml"

        # tomli_w doesn't easily support per-line comments, so we'll do it manually or just put a block comment
        content = [self._get_header(), "[tools]"]
        for rt in self.result.resolved:
            content.append(f'{rt.name} = "latest"  # Source: {rt.backend}:{rt.registry_entry}')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_shorthands_toml(self) -> Path:
        path = self.output_dir / self.shorthands_file
        shorthands = {}

        github_pattern = re.compile(r"github:([a-zA-Z0-9\-\._/]+)")

        for ut in self.result.unresolved:
            for action in ut.suggested_actions:
                match = github_pattern.search(action)
                if match:
                    repo = match.group(1)
                    if "/" in repo:
                        shorthands[ut.name] = f"github:{repo}"
                        break

        content = [self._get_header()]
        for name, repo in shorthands.items():
            content.append(f'{name} = "{repo}"')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_bootstrap_sh(self) -> Path:
        path = self.output_dir / "bootstrap.sh"

        content = [
            "#!/usr/bin/env bash",
            # Strict mode: fail-fast on errors, undefined vars, and broken pipes.
            # Without this, a mid-script install failure leaves the system in a partial state.
            "set -euo pipefail",
            "",
            self._get_header(),
            "# This script contains installation fallback commands for tools not resolved by mise.",
            "# Only commands matching an allowlisted install prefix are emitted. Other entries are skipped.",
            "",
        ]

        github_pattern = re.compile(r"github:[a-zA-Z0-9\-\._/]+")

        any_tools = False
        for ut in self.result.unresolved:
            # GitHub-shorthand candidates go to shorthands.toml, not bootstrap.sh
            if any(github_pattern.search(action) for action in ut.suggested_actions):
                continue

            # Find an allowlisted install command from the suggested actions.
            # The allowlist + metacharacter filter prevents shell injection if suggested_actions
            # is ever sourced from untrusted input (currently internal, but defense in depth).
            install_cmd = next(
                (action for action in ut.suggested_actions if _is_safe_install_command(action)),
                None,
            )

            if install_cmd is None:
                # Either no suggested actions, or none passed validation. Skip with a log
                # so the user can audit what was rejected without the script being unsafe.
                if ut.suggested_actions:
                    logger.warning(
                        "Skipping bootstrap entry for %r: no suggested_action matches the install allowlist",
                        ut.name,
                    )
                continue

            any_tools = True
            source = "unknown"
            if ut.original.installed_by:
                source = ", ".join([str(s) for s in ut.original.installed_by])

            content.append(f"# Tool: {ut.name}")
            content.append(f"# Source: {source}")
            content.append(install_cmd)
            content.append("")

        if not any_tools:
            content.append("# No fallback tools identified.")

        path.write_text("\n".join(content) + "\n")
        # Make executable
        with contextlib.suppress(OSError):
            path.chmod(0o755)

        return path


def register(
    result: ResolutionResult, output_dir: Path | str = ".", shorthands_file: str = "shorthands.toml"
) -> RegistrationResult:
    registrar = Registrar(result, output_dir=output_dir, shorthands_file=shorthands_file)
    return registrar.generate_artifacts()
