import contextlib
import re
from datetime import datetime
from pathlib import Path

from mymise.models import RegistrationResult, ResolutionResult


class Registrar:
    def __init__(self, result: ResolutionResult, output_dir: Path | str = ".", shorthands_file: str = "shorthands.toml"):
        self.result = result
        self.output_dir = Path(output_dir)
        self.shorthands_file = shorthands_file
        self.version = "0.1.0"  # Could be loaded from pyproject.toml in a real scenario

    def generate_artifacts(self) -> RegistrationResult:
        """Generate mise.toml, shorthands.toml, and bootstrap.sh."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        github_pattern = re.compile(r"github:[a-zA-Z0-9\-\._/]+")
        
        # Calculate counts for summary/result
        shorthands_count = 0
        bootstrap_count = 0
        
        for ut in self.result.unresolved:
            is_github = any(github_pattern.search(action) for action in ut.suggested_actions)
            if is_github:
                shorthands_count += 1
            else:
                pkgs = ["apt install", "cargo install", "npm install", "pip install", "go install"]
                if any(any(x in action for x in pkgs) for action in ut.suggested_actions) or ut.suggested_actions:
                    bootstrap_count += 1

        artifacts = {
            "mise.toml": str(self._generate_mise_toml()),
            self.shorthands_file: str(self._generate_shorthands_toml()),
            "bootstrap.sh": str(self._generate_bootstrap_sh()),
        }

        return RegistrationResult(
            registration_timestamp=datetime.now(),
            artifacts=artifacts,
            resolved_count=len(self.result.resolved),
            shorthands_count=shorthands_count,
            bootstrap_count=bootstrap_count,
        )

    def _get_header(self) -> str:
        timestamp = datetime.now().isoformat(sep=" ", timespec="seconds")
        return (
            f"# Generated by mymise v{self.version}\n"
            f"# Timestamp: {timestamp}\n"
            "# ----------------------------------------------------------------------------\n"
        )

    def _generate_mise_toml(self) -> Path:
        path = self.output_dir / "mise.toml"

        # tomli_w doesn't easily support per-line comments, so we'll do it manually or just put a block comment
        content = [self._get_header(), "[tools]"]
        for rt in self.result.resolved:
            content.append(f'{rt.name} = "latest"  # Source: {rt.backend}:{rt.registry_entry}')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_shorthands_toml(self) -> Path:
        path = self.output_dir / self.shorthands_file
        shorthands = {}

        github_pattern = re.compile(r"github:([a-zA-Z0-9\-\._/]+)")

        for ut in self.result.unresolved:
            for action in ut.suggested_actions:
                match = github_pattern.search(action)
                if match:
                    repo = match.group(1)
                    if "/" in repo:
                        shorthands[ut.name] = f"github:{repo}"
                        break

        content = [self._get_header()]
        for name, repo in shorthands.items():
            content.append(f'{name} = "{repo}"')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_bootstrap_sh(self) -> Path:
        path = self.output_dir / "bootstrap.sh"

        content = [
            "#!/usr/bin/env bash",
            self._get_header(),
            "# This script contains installation fallback commands for tools not resolved by mise.",
            "",
        ]

        github_pattern = re.compile(r"github:[a-zA-Z0-9\-\._/]+")

        any_tools = False
        for ut in self.result.unresolved:
            # Check if it was NOT a GitHub tool (those go to shorthands.toml)
            is_github = any(github_pattern.search(action) for action in ut.suggested_actions)
            if is_github:
                continue

            # Find a command-like suggestion
            install_cmd = None
            pkgs = ["apt install", "cargo install", "npm install", "pip install", "go install"]
            for action in ut.suggested_actions:
                if any(x in action for x in pkgs):
                    install_cmd = action
                    break

            if not install_cmd and ut.suggested_actions:
                install_cmd = ut.suggested_actions[0]

            if install_cmd:
                any_tools = True
                source = "unknown"
                if ut.original.installed_by:
                    source = ", ".join([str(s) for s in ut.original.installed_by])

                content.append(f"# Tool: {ut.name}")
                content.append(f"# Source: {source}")
                content.append(f"{install_cmd}")
                content.append("")

        if not any_tools:
            content.append("# No fallback tools identified.")

        path.write_text("\n".join(content) + "\n")
        # Make executable
        with contextlib.suppress(OSError):
            path.chmod(0o755)

        return path


def register(
    result: ResolutionResult, output_dir: Path | str = ".", shorthands_file: str = "shorthands.toml"
) -> RegistrationResult:
    registrar = Registrar(result, output_dir=output_dir, shorthands_file=shorthands_file)
    return registrar.generate_artifacts()
