import re
from datetime import datetime
from pathlib import Path

from mymise.models import ResolutionResult


class Registrar:
    def __init__(self, result: ResolutionResult, output_dir: Path | str = "."):
        self.result = result
        self.output_dir = Path(output_dir)
        self.version = "0.1.0"  # Could be loaded from pyproject.toml in a real scenario

    def generate_artifacts(self) -> dict[str, Path]:
        """Generate mise.toml, shorthands.toml, and bootstrap.sh."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        artifacts = {
            "mise.toml": self._generate_mise_toml(),
            "shorthands.toml": self._generate_shorthands_toml(),
            "bootstrap.sh": self._generate_bootstrap_sh(),
        }

        return artifacts

    def _get_header(self) -> str:
        timestamp = datetime.now().isoformat(sep=" ", timespec="seconds")
        return (
            f"# Generated by mymise v{self.version}\n"
            f"# Timestamp: {timestamp}\n"
            "# ----------------------------------------------------------------------------\n"
        )

    def _generate_mise_toml(self) -> Path:
        path = self.output_dir / "mise.toml"
        
        # tomli_w doesn't easily support per-line comments, so we'll do it manually or just put a block comment
        content = [self._get_header(), "[tools]"]
        for rt in self.result.resolved:
            content.append(f'{rt.name} = "latest"  # Source: {rt.backend}')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_shorthands_toml(self) -> Path:
        path = self.output_dir / "shorthands.toml"
        shorthands = {}
        
        github_pattern = re.compile(r"github:([a-zA-Z0-9\-\._/]+)")

        for ut in self.result.unresolved:
            for action in ut.suggested_actions:
                match = github_pattern.search(action)
                if match:
                    repo = match.group(1)
                    if "/" in repo:
                        shorthands[ut.name] = f"github:{repo}"
                        break
        
        content = [self._get_header()]
        for name, repo in shorthands.items():
            content.append(f'{name} = "{repo}"')

        path.write_text("\n".join(content) + "\n")
        return path

    def _generate_bootstrap_sh(self) -> Path:
        path = self.output_dir / "bootstrap.sh"
        
        content = [
            "#!/usr/bin/env bash",
            self._get_header(),
            "# This script contains installation fallback commands for tools not resolved by mise.",
            "",
        ]

        github_pattern = re.compile(r"github:[a-zA-Z0-9\-\._/]+")
        
        any_tools = False
        for ut in self.result.unresolved:
            # Check if it was NOT a GitHub tool (those go to shorthands.toml)
            is_github = any(github_pattern.search(action) for action in ut.suggested_actions)
            if is_github:
                continue
            
            # Find a command-like suggestion
            install_cmd = None
            for action in ut.suggested_actions:
                if any(x in action for x in ["apt install", "cargo install", "npm install", "pip install", "go install"]):
                    install_cmd = action
                    break
            
            if not install_cmd and ut.suggested_actions:
                install_cmd = ut.suggested_actions[0]
            
            if install_cmd:
                any_tools = True
                source = "unknown"
                if ut.original.installed_by:
                    source = ", ".join([str(s) for s in ut.original.installed_by])
                
                content.append(f"# Tool: {ut.name}")
                content.append(f"# Source: {source}")
                content.append(f"{install_cmd}")
                content.append("")

        if not any_tools:
            content.append("# No fallback tools identified.")

        path.write_text("\n".join(content) + "\n")
        # Make executable
        try:
            path.chmod(0o755)
        except OSError:
            pass
            
        return path


def register(result: ResolutionResult, output_dir: Path | str = ".") -> dict[str, Path]:
    registrar = Registrar(result, output_dir=output_dir)
    return registrar.generate_artifacts()
